# Generated by Django 4.0.4 on 2022-04-22 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testblog',
            name='name',
        ),
        migrations.AddField(
            model_name='testblog',
            name='Desc',
            field=models.CharField(default='', max_length=750),
        ),
        migrations.AddField(
            model_name='testblog',
            name='Preview_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='testblog',
            name='Topic',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='testblog',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.testblog')),
            ],
        ),
    ]
