# Generated by Django 4.0.4 on 2022-04-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_testblog_name_testblog_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='post',
            new_name='x',
        ),
    ]
