# Generated by Django 4.0.4 on 2022-05-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Preview_img',
        ),
        migrations.AddField(
            model_name='post',
            name='Link',
            field=models.TextField(default=''),
        ),
    ]
